using System;
using System.ComponentModel;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome v6.7.1 icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <remark>This code was automatically generated by FA2CS (https://github.com/matthewrdev/fa2cs).</remark>
    /// </summary>
    public static partial class FontAwesomeIcons
    {
        /// <summary>
        /// fa-volume-high unicode value ("\uf028").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro), Thin (Pro)
        /// <para/>
        /// Introduced in '1.0.0', Last Modified in '6.7.0'.
        /// <para/>
        /// See https://fontawesome.com/icons/volume-high
        /// </summary>
        [Description("volume-high")]
        public const string VolumeHigh = "\uf028";

        /// <summary>
        /// fa-volume-low unicode value ("\uf027").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro), Thin (Pro)
        /// <para/>
        /// Introduced in '1.0.0', Last Modified in '6.7.0'.
        /// <para/>
        /// See https://fontawesome.com/icons/volume-low
        /// </summary>
        [Description("volume-low")]
        public const string VolumeLow = "\uf027";

        /// <summary>
        /// fa-volume-off unicode value ("\uf026").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro), Thin (Pro)
        /// <para/>
        /// Introduced in '1.0.0', Last Modified in '6.7.0'.
        /// <para/>
        /// See https://fontawesome.com/icons/volume-off
        /// </summary>
        [Description("volume-off")]
        public const string VolumeOff = "\uf026";

        /// <summary>
        /// fa-volume-slash unicode value ("\uf2e2").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro), Thin (Pro)
        /// <para/>
        /// Introduced in '5.0.0', Last Modified in '6.7.0'.
        /// <para/>
        /// See https://fontawesome.com/icons/volume-slash
        /// </summary>
        [Description("volume-slash")]
        public const string VolumeSlash = "\uf2e2";

        /// <summary>
        /// fa-volume-xmark unicode value ("\uf6a9").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro), Thin (Pro)
        /// <para/>
        /// Introduced in '5.3.0', Last Modified in '6.7.0'.
        /// <para/>
        /// See https://fontawesome.com/icons/volume-xmark
        /// </summary>
        [Description("volume-xmark")]
        public const string VolumeXmark = "\uf6a9";
    }
}
